<?php 
    function fellowship_testimonials_menu() {
        $items = array();
        $items["fellowship-testimonials"] = array(
            "title" => "Testimonials by FOSSEE Summer Fellows",
            "page callback" => "fellowship_testimonials_display_all",
            "access arguments" => array("view fellowship_testimonials"),
            "type" => MENU_CALLBACK
        );
        $items["fellowship-testimonials/add"] = array(
            "title" => "Add fellowship testimonials",
            "page callback" => "fellowship_testimonials_add_all",
            "access arguments" => array("manage fellowship_testimonials"),
            "type" => MENU_CALLBACK,
            'file' => 'testimonials_add.inc'
        );
        $items["fellowship-testimonials/edit"] = array(
            "title" => "Edit fellowship_testimonials",
            "page callback" => "fellowship_testimonials_edit_all",
            "access arguments" => array("manage fellowship_testimonials"),
            "type" => MENU_CALLBACK,
            'file' => 'testimonials_add.inc'
        );
        $items["fellowship-testimonials/delete"] = array(
            "title" => "Delete Testimonial",
            "page callback" => "fellowship_testimonials_delete_all",
            "access arguments" => array("manage fellowship_testimonials"),
            "type" => MENU_CALLBACK
        );
        return $items;
    }

    function fellowship_testimonials_permission() {
        return array(
            "view fellowship_testimonials" => array (
            "title" => t("view fellowship_testimonials"),
            'restrict access' => TRUE,
            ),
            "manage fellowship_testimonials" => array (
            "title" => t("manage fellowship_testimonials"),
            'restrict access' => TRUE,
            ),
        );
    }
    function fellowship_testimonials_display_all() {
        $page_content = "";
        /*$query = "
            SELECT * FROM fellowship_testimonials
            ORDER BY id DESC
        ";
        $result = pager_query($query, 4, 0, "SELECT COUNT(*) FROM fellowship_testimonials");*/
         $query = db_select('fellowship_testimonials');
         $query->fields('fellowship_testimonials');
         $query->orderBy('year', 'DESC');
         $result = $query->extend('PagerDefault')->limit(3)->execute();
        
        $page_content .= "<div id='fellowship_testimonials-wrapper'>";
        while($row = $result->fetchObject()) {
            $speakerquery = db_select('fellows');
            $speakerquery->fields('fellows');
            $speakerquery->condition('t_id', $row->id);
            $speakerresult = $speakerquery->execute();
           
            $page_content .= "
              <div class='container-testimonial'>
 <video title='' controls='' preload='' data-setup='{}' width='500' height='400'>
 <source src={$row->testimonial_video} type='video/mp4'>
                                </video> ";
 while($speakerrow = $speakerresult->fetchObject()){
        $page_content .= "<p><span>{$speakerrow->name}</span><br>Institute: {$speakerrow->institute}, {$speakerrow->place}<br><br><span style='margin-right:0;'>";
    }
            $page_content .= "Fellowship task</span>: {$row->fellowship_task}
            <br><br><span>Fellowship Year</span>: {$row->year}</p></div>";
            
    }
        $page_content .= "</div> <!-- /#fellowship_testimonials-wrapper -->";
        //$page_content .= theme("pager", NULL, 4, 0);
        $page_content .= theme('pager', array('header' => NULL, 'rows' => 4 ));
        return $page_content;
    }

    function fellowship_testimonials_init() {
        drupal_add_css(drupal_get_path("module", "fellowship_testimonials") . "/css/fellowship_testimonials.css");
    }
?>
